### ISSUE TITLE
Experiment Details in Search (US 05.02.01)

### ISSUE THREAD

**Issue by jamessch16** [CMPUT301W21T21-H03/DivineInspiration#15]
**User Story**: As an experimenter, I want search results to show each experiment with its description, owner username, and status.

**Dependencies**: #2, #11

**Rationale**: Showing basic experiment information allows users to find relevant experiments more quickly. Improves productivity.

**Story Points**: 3

**Risk Level**: Low

**Comment by jamessch16** [comment]
Right now, only the experiment name is displayed. Need to add owner, status, and description.

**Comment by iAniket23** [comment]
what is the meaning of this issue?
