### ISSUE TITLE
Publish experiment as owner (US 01.01.01)

### ISSUE THREAD

**Issue by goldentoaste** [CMPUT301W21T21-H03/DivineInspiration#2]
**User story**: As an owner, I want to publish an experiment with a description, a region, and a minimum
 number of trials.

**Dependencies**: #11

**Rationale**: To allow users to start new experiments, which other users can contribute trials to.

**Story points**: 5

**Risk level**: low, implementation of this feature is essential and should not be difficult.

**Comment by jamessch16** [comment]
Need to implement the ability to specify a minimum number of trials.
